<a href="https://colab.research.google.com/github/Hashhhhhhhh/ML-with-Python/blob/main/Handling_Imbalanced_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

An imbalanced data :

The one with unequal class distribution

In [5]:
import numpy as np
import pandas as pd

In [6]:
df=pd.read_csv('/content/credit_data.csv')
df.head(6)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0
5,2,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,...,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0.0

In [7]:
df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
39697,39927,-1.466679,2.425732,0.877724,3.950765,0.762477,1.162748,0.575625,-0.288354,-1.357990,...,0.186051,0.571010,-0.107517,-0.754306,-0.752828,0.113179,-2.079421,-0.809173,1.50,0.0
39698,39927,-0.523165,-0.100021,0.892966,-1.900405,-0.156870,-0.783894,0.917683,-0.308345,-1.305284,...,-0.082504,-0.414677,-0.063392,-0.087455,-0.303383,-0.682889,-0.178417,-0.137169,100.92,0.0
39699,39928,-2.768425,-1.007072,2.151127,0.117797,1.283178,1.869731,-0.562240,0.820374,0.348797,...,-0.182963,0.778210,0.904077,-1.288631,0.212441,0.483975,-0.027614,-0.582813,11.99,0.0
39700,39928,1.201327,0.158614,-0.325263,0.471667,0.086446,-0.770357,0.422151,-0.205277,-0.451865,...,0.027664,-0.018485,-0.199382,0.053605,0.683829,0.428416,-0.077342,-0.006394,45.00,0.0
39701,39929,1.097669,-1.315782,0.659681,-0.683915,-1.342612,0.332629,-1.110900,0.194811,-0.248825,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

Typical classification problem.

In [9]:
df.shape

(39702, 31)

In [10]:
#Distribution of the two classes
df['Class'].value_counts()

Class
0.0    39597
1.0      104
Name: count, dtype: int64

0 : Legit transactions


1 : Fradulent transactions

In [11]:
#Seperating legit and fraud
legit=df[df.Class==0]
fraud=df[df.Class==1]
print(legit.shape)
print(fraud.shape)

(39597, 31)
(104, 31)

Under sampling technique to handle imbalanced data.

Build a small dataset containing similar distribution of legit and fraudulent transactions.

In [18]:
legit_sample=legit.sample(n=104)
print(legit_sample.shape)

(104, 31)

In [19]:
#concatenate the two dataframes
new_df=pd.concat([legit_sample,fraud],axis=0)
new_df.shape

(208, 31)

In [20]:
new_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
13843,24573,1.141840,0.361106,-1.320234,0.774945,0.851042,-1.328003,1.284073,-0.685476,0.399960,...,0.195535,0.728878,-0.512672,0.167776,1.273774,0.961344,-0.160089,-0.022905,107.82,0.0
15475,26862,-0.622932,1.103183,1.267262,0.117764,-0.379612,-1.241877,0.569549,0.040425,0.114028,...,-0.298077,-0.836142,0.077085,0.595165,-0.224855,0.064099,0.337891,0.162390,11.36,0.0
26912,34305,0.844454,-0.220778,0.344528,1.214150,0.336553,1.599756,-0.230794,0.582850,0.051724,...,0.088545,0.413684,-0.001727,-0.811098,0.328577,-0.248754,0.077322,0.006400,70.00,0.0
5004,4571,1.014703,-0.084558,0.660588,0.752448,-0.653888,-0.726676,-0.075259,-0.117052,1.202625,...,-0.388242,-1.200618,0.152152,0.451826,-0.042264,0.025590,-0.090923,0.020571,101.38,0.0
800,608,-0.290389,-0.315750,1.365425,-1.008311,-0.581263,-0.297351,-0.293730,0.012441,-2.980624,...,-0.027130,0.301992,-0.159177,0.078367,0.164979,0.244876,0.101683,0.067289,15.00,0.0

In [21]:
new_df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
30473,35942,-4.194074,4.382897,-5.118363,4.455230,-4.812621,-1.224645,-7.281328,3.332250,-3.679659,...,1.550473,0.614573,0.028521,0.013704,-0.149512,-0.131687,0.473934,0.473757,14.46,1.0
30496,35953,-4.844372,5.649439,-6.730396,5.252842,-4.409566,-1.740767,-6.311699,3.449167,-5.416284,...,1.194888,-0.845753,0.190674,-0.216443,-0.325033,-0.270328,0.210214,0.391855,111.70,1.0
31002,36170,-5.685013,5.776516,-7.064977,5.902715,-4.715564,-1.755633,-6.958679,3.877795,-5.541529,...,1.128641,-0.962960,-0.110045,-0.177733,-0.089175,-0.049447,0.303445,0.219380,111.70,1.0
33276,37167,-7.923891,-5.198360,-3.000024,4.420666,2.272194,-3.394483,-5.283435,0.131619,0.658176,...,-0.734308,-0.599926,-4.908301,0.410170,-1.167660,0.520508,1.937421,-1.552593,12.31,1.0
39183,39729,-0.964567,-1.643541,-0.187727,1.158253,-2.458336,0.852222,2.785163,-0.303609,0.940006,...,0.447180,0.536204,1.634061,0.203839,0.218749,-0.221886,-0.308555,-0.164500,776.83,1.0

In [22]:
new_df['Class'].value_counts()

Class
0.0    104
1.0    104
Name: count, dtype: int64